package Frames;

import Panels.ManagerPanel;
import People.Manager;
import java.awt.Dimension;
import java.awt.Toolkit;

public class Main extends javax.swing.JFrame{
    private final Toolkit t;
    private final Dimension d;

    /**
     * Creates new form Main
     */
    public Main() {
        t = Toolkit.getDefaultToolkit();
        d = t.getScreenSize();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        
        setTitle("آزمون یار");
        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(26, 33, 38));
        setBounds((d.width)/4, (d.height)/4, (d.width)/2,(d.height) /2);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setForeground(java.awt.Color.darkGray);
        setName("Azmoon"); // NOI18N
        setPreferredSize(new Dimension((d.width)/2, (d.height)/2));
        setSize((d.width) /2, (d.height)/2);
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel1.setBackground(new java.awt.Color(26, 33, 38));
        jLabel1.setFont(new java.awt.Font("B Nazanin", 1, getHeight() / 10)); // NOI18N
        jLabel1.setText("آزمون یار");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel1.setInheritsPopupMenu(false);
        getContentPane().add(jLabel1);
        jLabel1.setBounds(getWidth() * 3 / 8, getHeight() / 15, getWidth() / 2, getHeight() / 9);

        jPanel1.setBackground(new java.awt.Color(255, 102, 102));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "پنل مدیر", 
                javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, 
                new java.awt.Font("B Nazanin", 1, d.height /24))); // NOI18N
        jPanel1.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(null);

        jButton2.setFont(new java.awt.Font("B Nazanin", 1, d.height /28)); // NOI18N
        jButton2.setText("ورود");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(getWidth() / 15, getHeight() / 4, getWidth() * 3 / 8, getHeight() * 5 / 8);
        jButton1.setBounds(jPanel1.getWidth() * 5/ 16, jPanel1.getHeight() / 2, jPanel1.getWidth() * 3 / 8, jPanel1.getHeight() / 8);

        jPanel2.setBackground(new java.awt.Color(255, 102, 102));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, 
                "پنل دانشجو", javax.swing.border.TitledBorder.CENTER, 
                javax.swing.border.TitledBorder.TOP, new java.awt.Font("B Nazanin", 1, d.height /24))); // NOI18N
        jPanel2.setForeground(new java.awt.Color(0, 0, 0));
        jPanel2.setLayout(null);

        jButton1.setFont(new java.awt.Font("B Nazanin", 1, d.height /28)); // NOI18N
        jButton1.setText("ورود");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2);
        

        getContentPane().add(jPanel2);
        jPanel2.setBounds(getWidth() * 8 / 15, getHeight() / 4, getWidth() * 3 / 8, getHeight() * 5 / 8);
        jButton2.setBounds(jPanel2.getWidth() * 5/ 16, jPanel2.getHeight() / 2, jPanel2.getWidth() * 3 / 8, jPanel2.getHeight() / 8);

        getAccessibleContext().setAccessibleName("Azmoon Yar");

        pack();
    }// </editor-fold>                        

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
    }                                        

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
        this.removeAll();
        new ManagerPanel(new Manager("Ali", "A", "83293fdsdf"), this).setVisible(true);
    }                                        

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Init.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Init.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Init.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Init.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration    
}
